apiVersion: v1
kind: Service
metadata:
  name: restui-service
spec:
  selector:
    app: restui-app
  ports:
    - protocol: 'TCP'
      port: 8081
      targetPort: 8081
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer