apiVersion: v1
kind: Service
metadata:
  name: tsp-backend-service
spec:
  selector:
    app: tspapi-app
  ports:
    - protocol: 'TCP'
      port: 8080
      targetPort: 8080
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer